//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

		public class AudioList : SingletonBehaviour<AudioList>
		{
			public  AudioClip BewareSomeoneElseKnowsYouHaveInformation;
			public  AudioClip NoInformation;
			public  AudioClip InThisRoomPreviousGivenSameInfo;
			public  AudioClip PassHeadphones;
			public  AudioClip NextGivenSame;
			public AudioClip NextGivenName;
			public  AudioClip PreviousGivenSame;
			public  AudioClip ToWhoeverHas;
			public AudioClip TurnsIdentityAndLocation;
			
			public  AudioClip ThereIsA;
			public  AudioClip ThereIsAnItem;
			
			public  AudioClip IsInfact;
			public  AudioClip IsNotInfact;
			
			public  AudioClip ArticleThe;
			public  AudioClip PrepositionIn;
			public  AudioClip PrepositionBehind;
			public  AudioClip PrepositionUnder;

			public  AudioClip NumberZero;
			public  AudioClip NumberOne;
			public  AudioClip NumberTwo;
			public  AudioClip NumberThree;
			public  AudioClip NumberFour;
			public  AudioClip NumberFive;
			public  AudioClip NumberSix;
			
			public  AudioClip LocationCleanVent;
			public  AudioClip LocationGrate;
			public  AudioClip LocationGreenBed;
			public  AudioClip LocationLamp;
			public  AudioClip LocationRedBed;
			public  AudioClip LocationRustyVent;
			public  AudioClip LocationShelf;
			public  AudioClip LocationSink;
			public  AudioClip LocationToilet;
			
			public  AudioClip ObjectANonItem;
			public  AudioClip ObjectBoobyTrap;
			public  AudioClip ObjectFakeKnife;
			public  AudioClip ObjectGasMask;
			public  AudioClip ObjectGasTrap;
			public  AudioClip ObjectRealKnife;

			public static AudioClip PlaceholderItem;
			public static AudioClip PlaceholderLocation;
			public static AudioClip PlaceholderWarningTime;
			public static AudioClip PlaceholderError;
		}


